---
title: "02-lineage-annotation"
author: "Sam Chen"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: TRUE
---

## Setup

```{r load-packages, message=FALSE, warning=FALSE}
# Load libraries
library(rprojroot)
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(DoubletFinder)
library(tidyverse)
library(SeuratObject)
library(scCustomize)
library(presto)
library(SingleR)
library(celldex)

# Define directories
root_dir <- find_root(has_dir(".git"))
data_dir <- file.path(root_dir, "data", "v5")
analysis_dir <- file.path(root_dir, "analyses", "main-lineage-processing")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

# Source custom theme
source(file.path(root_dir, "figures", "theme.R"))

# Source function
source(file.path(analysis_dir, "util", "run_doubletfinder.R"))
source(file.path(analysis_dir, "util", "run_soupx.R"))

# set random seed
set.seed(1234)
```

## Load data
```{r load-seurat-object}
obj <- readRDS(file.path(results_dir, "cart_integrated.rds"))
```

## SingleR annotation
```{r singleR-annotation}
# Load reference dataset
general_ref <- MouseRNAseqData()
immgen_ref <- ImmGenData()

# Run SingleR
general_annotations <- SingleR::SingleR(
  test = GetAssayData(obj, layer = "data"),
  ref = general_ref,
  labels = general_ref$label.main
)

immgen_annotations <- SingleR::SingleR(
  test = GetAssayData(obj, layer = "data"),
  ref = immgen_ref,
  labels = immgen_ref$label.main
)
# Add annotations to metadata
obj$general_label <- general_annotations$labels
obj$immgen_label <- immgen_annotations$labels
```

## Visualize annotations
```{r visualize-annotations, fig.height=6, fig.width=12}
p1 <- DimPlot(obj, group.by = "general_label", label = TRUE, repel = TRUE, reduction = "umap", pt.size = 0.5, alpha = 0.5) + ggtitle("General Mouse Cell Types")
p2 <- DimPlot(obj, group.by = "immgen_label", label = TRUE, repel = TRUE, reduction = "umap", pt.size = 0.5, alpha = 0.5) + ggtitle("ImmGen Cell Types")
p1 + p2
```

## Annotation summary
```{r annotation-summary-general, fig.height=12, fig.width=12}
SingleR::plotScoreHeatmap(general_annotations)
SingleR::plotDeltaDistribution(general_annotations)
```
```{r annotation-summary-immgen, fig.height=12, fig.width=12}
SingleR::plotScoreHeatmap(immgen_annotations)
SingleR::plotDeltaDistribution(immgen_annotations)
```

## Clusters vs SingleR labels
```{r clusters-vs-labels-general, fig.height=6, fig.width=6}
general_annot <- as.data.frame(table(
  Cluster = obj$seurat_clusters,
  Annotation = obj$general_label
)) %>%
  group_by(Cluster) %>%
  mutate(Percentage = Freq / sum(Freq) * 100) %>%
  ungroup()

general_annot %>%
  ggplot(aes(x = Annotation, y = fct_rev(Cluster), fill = Percentage)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "D") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    plot.title = element_text(hjust = 0.5, face = "bold")
  ) +
  labs(x = "Annotation", y = "Seurat Cluster",
       fill = "Percentage",
       title = "Seurat Cluster – General Annotation Composition Heatmap")
```

```{r clusters-vs-labels-immgen, fig.height=6, fig.width=6}
general_annot <- as.data.frame(table(
  Cluster = obj$seurat_clusters,
  Annotation = obj$immgen_label
)) %>%
  group_by(Cluster) %>%
  mutate(Percentage = Freq / sum(Freq) * 100) %>%
  ungroup()

general_annot %>%
  ggplot(aes(x = Annotation, y = fct_rev(Cluster), fill = Percentage)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "D") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    plot.title = element_text(hjust = 0.5, face = "bold")
  ) +
  labs(x = "Annotation", y = "Seurat Cluster",
       fill = "Percentage",
       title = "Seurat Cluster – Immgen Annotation Composition Heatmap")
```

## Check main lineage marker genes
```{r marker-gene-expression, fig.height=6, fig.width=6}
# Macrophages
FeaturePlot_scCustom(obj, features = c("Lyz2", "Adgre1", "Cd68", "C1qa"), reduction = "umap", colors_use = viridis_light_high)
# Microglia
FeaturePlot_scCustom(obj, features = c("P2ry12", "Tmem119", "Sall1", "Hexb"), reduction = "umap", colors_use = viridis_light_high)
# DC
FeaturePlot_scCustom(obj, features = c("Cd74", "Flt3", "Itgax", "Cd209a"), reduction = "umap", colors_use = viridis_light_high)
# T cells
FeaturePlot_scCustom(obj, features = c("Cd3d", "Cd3e", "Trac", "Gzmb"), reduction = "umap", colors_use = viridis_light_high)
# B cells
FeaturePlot_scCustom(obj, features = c("Cd19", "Cd79a", "Ms4a1", "Cd79b"), reduction = "umap", colors_use = viridis_light_high)
# Fibroblasts
FeaturePlot_scCustom(obj, features = c("Pdgfra", "Col1a1", "Dcn", "Lum"), reduction = "umap", colors_use = viridis_light_high)
# Endothelial Cells
FeaturePlot_scCustom(obj, features = c("Pecam1", "Cdh5", "Kdr", "Flt1"), reduction = "umap", colors_use = viridis_light_high)
# Neurons
FeaturePlot_scCustom(obj, features = c("Map2", "Tubb3", "Rbfox3", "Syt1"), reduction = "umap", colors_use = viridis_light_high)
```

## Manually annotate lineages to clean up labels
```{r manual-annotation}
new_cluster_ids <- c(
  "0"= "Microglia", 
  "1"= "Microglia", 
  "2"= "Macrophages", 
  "3"= "Neurons",
  "4"= "Neurons",
  "5"= "Macrophages",
  "6"= "Microglia", 
  "7"= "NK/T cells",
  "8"= "Microglia",
  "9"= "Endothelial cells",
  "10"= "Astrocytes",
  "11"= "Fibroblasts",
  "12"= "B cells",
  "13"= "Neurons",
  "14"= "Fibroblasts",
  "15"= "Monocytes",
  "16"= "Neutrophils",
  "17"= "Microglia",
  "18"= "Oligodendrocytes",
  "19"= "Dendritic cells",
  "20"= "Macrophages",
  "21"= "Neurons",
  "22"= "Macrophages",
  "23"= "Neurons",
  "24"= "B cells",
  "25"= "Dendritic cells",
  "26"= "Fibroblasts",
  "27"= "Epithelial cells",
  "28"= "Epithelial cells",
  "29"= "NK/T cells",
  "30"= "Neutrophils",
  "31"= "Mast cells",
  "32"= "B cells"
)

obj$cell_type <- plyr::mapvalues(
  x = as.character(obj$seurat_clusters),
  from = names(new_cluster_ids),
  to = as.vector(new_cluster_ids)
)
```

## Visualize manual annotations
```{r visualize-manual-annotations, fig.height=6, fig.width=6}
DimPlot(obj, group.by = "cell_type", size = 0.5, alpha = 0.5, label = TRUE, repel = TRUE, reduction = "umap") + ggtitle("Lineage Annotations")
ggsave(filename = file.path(plot_dir, "cart_umap_lineage_annotations.png"), width = 6, height = 6)

DimPlot(obj, group.by = "seurat_clusters", size = 0.5, alpha = 0.5, label = TRUE, repel = TRUE, reduction = "umap") + ggtitle("Seurat Clusters")
ggsave(filename = file.path(plot_dir, "cart_umap_clusters.png"), width = 6, height = 6)
```

## Identify and export marker genes
```{r identify-markers}
cluster_markers <- FindAllMarkers(obj, 
                                 only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, 
                                 group.by = 'seurat_clusters', assay = 'RNA')

lineage_markers <- FindAllMarkers(obj, 
                                 only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, 
                                 group.by = 'cell_type', assay = 'RNA')

# Save markers
write.csv(cluster_markers, file = file.path(results_dir, "cart_cluster_markers.csv"), row.names = FALSE)
write.csv(lineage_markers, file = file.path(results_dir, "cart_lineage_markers.csv"), row.names = FALSE)
```

## Visualize top markers per lineage by heatmap
```{r visualize-top-markers-heatmap, fig.height=16, fig.width=8}
lineage_markers <- read.csv(file.path(results_dir, "cart_lineage_markers.csv"))

top50_markers <- lineage_markers %>%
  group_by(cluster) %>%
  top_n(n = 50, wt = avg_log2FC)

# scale top markers in RNA assay
obj <- ScaleData(obj, features = unique(top50_markers$gene), assay = "RNA")

# separate heatmap for each cluster, save in one pdf file
pdf(file = file.path(plot_dir, "cart_heatmap_top_lineage_markers.pdf"), width = 16, height = 8)
for (lineage in unique(top50_markers$cluster)) {
  markers <- top50_markers %>%
    filter(cluster == lineage) %>%
    pull(gene)
  
  p <- DoHeatmap(obj, features = markers, group.by = "cell_type", assay = "RNA", cells = 1:2000) +
    ggtitle(paste("Top Markers for", lineage)) +
    theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  
  print(p)
}
dev.off()
```

## Lineage dot plot
```{r lineage-dot-plot, fig.height=5, fig.width=8}
## stacked barplot
meta <- as.data.frame(obj@meta.data)
prop_df <- meta %>%
  dplyr::count(condition, cell_type) %>%
  group_by(condition) %>%
  mutate(prop = n / sum(n))

## dotplot of proportions
ggplot(prop_df, aes(x = condition, y = cell_type, size = prop, color = prop)) +
  geom_point() +
  scale_color_viridis_c() +
  scale_y_discrete(limits = rev) + 
  theme_classic() +
  ylab("Cluster") + 
  xlab("Condition")
ggsave(filename = file.path(plot_dir, "cart_dotplot_lineage_proportions.png"), width = 8, height = 5)
```

## Save annotated object
```{r save-annotated-object}
saveRDS(obj, file = file.path(results_dir, "cart_annotated.rds"))
```

## Session info
```{r session-info}
sessionInfo()
```