---
title: "02-one-sample-test.Rmd"
author: "Sam Chen"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: TRUE
---

## Setup

```{r load-packages, message=FALSE, warning=FALSE}
# Load libraries
library(rprojroot)
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(DoubletFinder)
library(tidyverse)
library(SeuratObject)
library(scCustomize)
library(presto)
library(pheatmap)

# Define directories
root_dir <- find_root(has_dir(".git"))
data_dir <- file.path(root_dir, "data", "v2")
analysis_dir <- file.path(root_dir, "analyses", "soupx-analysis")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

# Source custom theme
source(file.path(root_dir, "figures", "theme.R"))

# Source function
source(file.path(analysis_dir, "util", "run_doubletfinder.R"))
source(file.path(analysis_dir, "util", "run_soupx.R"))

# set random seed
set.seed(1234)
```

## Macrophage, microglia, and t cell markers
```{r define-marker-lists}
macrophage_genes <- c("Adgre1", "Cd68", "Lyz2", "Cd14")
microglia_genes <- c("Tmem119", "Hexb", "Sparc", "Csf1r")
tcell_genes <- c("Cd3d", "Cd3e", "Cd2", "Trac")
```

# Condition 1: Not running SoupX
Already performed in 01-ambient-assessment.Rmd
```{r visualize-no-soupx, fig.width=8, fig.height=6}
no_soupx <- readRDS(file.path(results_dir, "B7H3_pos_T_D2_no_soupx.rds"))
soupx_clusters <- read.csv(file.path(results_dir, "soupx_clusters_B7H3_pos_T_D2.csv"))

FeaturePlot_scCustom(no_soupx, features = macrophage_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(no_soupx, features = microglia_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(no_soupx, features = tcell_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
```

# Condition 2: SoupX with default parameters
```{r soupx-default}
# Load the raw data
raw_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "raw_bc"))
filt_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "filtered_bc"))

# intersect genes
common_genes <- intersect(rownames(raw_mat), rownames(filt_mat))
# subset and reorder them identically
raw_mat  <- raw_mat[common_genes, ]
filt_mat <- filt_mat[common_genes, ]

# Create SoupX object
sc <- SoupChannel(tod = raw_mat, toc = filt_mat)
sc <- setClusters(sc, soupx_clusters$seurat_clusters)
  
# Estimate contamination fraction
sc <- autoEstCont(sc)

# Adjust counts to remove contamination
clean_counts <- adjustCounts(sc, roundToInt = TRUE)
```

```{r process-soupx-default, warning=FALSE, message=FALSE}
# Create Seurat object with cleaned counts
soupx_default <- CreateSeuratObject(clean_counts, project = "B7H3_pos_T_D2_soupx_default", min.cells = 1, min.features = 50)
# Standard preprocessing
soupx_default <- NormalizeData(soupx_default)
soupx_default <- FindVariableFeatures(soupx_default, selection.method = "vst", nfeatures = 2000)
soupx_default <- ScaleData(soupx_default, features = VariableFeatures(soupx_default))
soupx_default <- RunPCA(soupx_default, features = VariableFeatures(soupx_default))
soupx_default <- RunUMAP(soupx_default, dims = 1:15)
```

```{r visualize-soupx-default, fig.width=8, fig.height=6}
FeaturePlot_scCustom(soupx_default, features = macrophage_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_default, features = microglia_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_default, features = tcell_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
```

# Condition 3: Manual contamination fraction 20%
```{r soupx-manual}
# Load the raw data
raw_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "raw_bc"))
filt_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "filtered_bc"))

# intersect genes
common_genes <- intersect(rownames(raw_mat), rownames(filt_mat))
# subset and reorder them identically
raw_mat  <- raw_mat[common_genes, ]
filt_mat <- filt_mat[common_genes, ]

# Create SoupX object
sc <- SoupChannel(tod = raw_mat, toc = filt_mat)
sc <- setClusters(sc, soupx_clusters$seurat_clusters)

# Manually setting contamination fraction to 20%
sc = setContaminationFraction(sc, 0.2)

# Adjust counts to remove contamination
clean_counts <- adjustCounts(sc, roundToInt = TRUE)
```

```{r process-soupx-manual, warning=FALSE, message=FALSE}
# Create Seurat object with cleaned counts
soupx_manual <- CreateSeuratObject(clean_counts, project = "B7H3_pos_T_D2_soupx_manual", min.cells = 1, min.features = 50)
# Standard preprocessing
soupx_manual <- NormalizeData(soupx_manual)
soupx_manual <- FindVariableFeatures(soupx_manual, selection.method = "vst", nfeatures = 2000)
soupx_manual <- ScaleData(soupx_manual, features = VariableFeatures(soupx_manual))
soupx_manual <- RunPCA(soupx_manual, features = VariableFeatures(soupx_manual))
soupx_manual <- RunUMAP(soupx_manual, dims = 1:15)
```

```{r visualize-soupx-manual, fig.width=8, fig.height=6}
FeaturePlot_scCustom(soupx_manual, features = macrophage_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_manual, features = microglia_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_manual, features = tcell_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
```

# Condition 4: SoupX with gene markers and no clusters
```{r soupx-markers-clusters}
# Load the raw data
raw_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "raw_bc"))
filt_mat <- Read10X(data.dir = file.path(data_dir, "B7H3_pos_T_D2", "filtered_bc"))

# intersect genes
common_genes <- intersect(rownames(raw_mat), rownames(filt_mat))
# subset and reorder them identically
raw_mat  <- raw_mat[common_genes, ]
filt_mat <- filt_mat[common_genes, ]

# Create SoupX object
sc <- SoupChannel(tod = raw_mat, toc = filt_mat)
sc <- setClusters(sc, soupx_clusters$seurat_clusters)

# manually estimating contamination fraction using marker genes without clusters
useToEst = estimateNonExpressingCells(sc, nonExpressedGeneList = list(
  mf = c("Adgre1", "Cd68", "Lyz2", "Cd14", "Mafb", "Fcgr1"),
  mg =  c("P2ry12", "Tmem119", "Hexb", "Sparc", "Csf1r"),
  t = c("Cd3d", "Cd3e", "Cd3g", "Cd2", "Trac"),
  nu = c("Snap25", "Syt1", "Rbfox3", "Camk2n1", "Map2"),
  ed = c("Cldn5", "Flt1", "Pecam1", "Kdr", "Vwf"),
  fb = c("Dcn", "Col1a1", "Col1a2", "Pdgfra", "Lum")), clusters = FALSE)

sc <- calculateContaminationFraction(sc, nonExpressedGeneList = list(
  mf = c("Adgre1", "Cd68", "Lyz2", "Cd14", "Mafb", "Fcgr1"),
  mg =  c("P2ry12", "Tmem119", "Hexb", "Sparc", "Csf1r"),
  t = c("Cd3d", "Cd3e", "Cd3g", "Cd2", "Trac"),
  nu = c("Snap25", "Syt1", "Rbfox3", "Camk2n1", "Map2"),
  ed = c("Cldn5", "Flt1", "Pecam1", "Kdr", "Vwf"),
  fb = c("Dcn", "Col1a1", "Col1a2", "Pdgfra", "Lum")
), useToEst = useToEst)

# Adjust counts to remove contamination
clean_counts <- adjustCounts(sc, roundToInt = TRUE)
```

```{r process-soupx-markers-clusters, warning=FALSE, message=FALSE}
# Create Seurat object with cleaned counts
soupx_markers_clusters <- CreateSeuratObject(clean_counts, project = "B7H3_pos_T_D2_soupx_markers_clusters", min.cells = 1, min.features = 50)
# Standard preprocessing
soupx_markers_clusters <- NormalizeData(soupx_markers_clusters)
soupx_markers_clusters <- FindVariableFeatures(soupx_markers_clusters, selection.method = "vst", nfeatures = 2000)
soupx_markers_clusters <- ScaleData(soupx_markers_clusters, features = VariableFeatures(soupx_markers_clusters))
soupx_markers_clusters <- RunPCA(soupx_markers_clusters, features = VariableFeatures(soupx_markers_clusters))
soupx_markers_clusters <- RunUMAP(soupx_markers_clusters, dims = 1:15)
```

```{r visualize-soupx-markers-clusters, fig.width=8, fig.height=6}
FeaturePlot_scCustom(soupx_markers_clusters, features = macrophage_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_markers_clusters, features = microglia_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
FeaturePlot_scCustom(soupx_markers_clusters, features = tcell_genes, reduction = "umap", 
                     pt.size = 0.1, alpha_exp = 0.25, colors_use = viridis_light_high)
```
