---
title: "04-dendritic-characterization"
author: "Sam Chen"
date: "`r Sys.Date()`"
output: html_document
  toc: TRUE
---

## Setup
```{r load-packages, message=FALSE, warning=FALSE}
# Load libraries
library(rprojroot)
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(SeuratObject)
library(scCustomize)
library(AUCell)
library(msigdbr)
library(sccomp)
library(pheatmap)
library(fgsea)

# Define directories
root_dir <- find_root(has_dir(".git"))
data_dir <- file.path(root_dir, "data", "v2")
analysis_dir <- file.path(root_dir, "analyses", "murine-cart-tumor")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

# Source custom theme
source(file.path(root_dir, "figures", "theme.R"))

# Source function
source(file.path(analysis_dir, "util", "run_doubletfinder.R"))
source(file.path(analysis_dir, "util", "run_soupx.R"))

# set random seed
set.seed(1234)
```

## Load Data
```{r load-data}
# Load Seurat object
dc_obj <- readRDS(file.path(results_dir, "cart_dc_subclusters.rds"))
```

## Re-run clusters in higher resolution
```{r rerun-clusters, message=FALSE, warning=FALSE}
dc_obj <- FindNeighbors(dc_obj, reduction = "integrated.cca", dims = 1:20)
dc_obj <- FindClusters(dc_obj, resolution = 0.5)
```

## Visualize myeloid subclusters
```{r visualize-myeloid-subclusters, fig.height=6, fig.width=12}
p1 <- DimPlot(dc_obj, reduction = "umap", group.by = "seurat_clusters", label = TRUE, label.size = 4) + 
  ggtitle("Subclusters")
p2 <- DimPlot(dc_obj, reduction = "umap", group.by = "cell_type", label = TRUE, label.size = 4) + 
  ggtitle("Main Lineages")

p1 + p2
```

## Cluster marker genes
```{r cluster-markers, message=FALSE, warning=FALSE}
cluster_markers <- FindAllMarkers(dc_obj,
                                  assay = "RNA",
                                  slot = "data",
                                  only.pos = TRUE,
                                  min.pct = 0.25,
                                  logfc.threshold = 0.25,
                                  test.use = "MAST")
```