---
title: "15-DC-AUCell"
author: "Bicna Song"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---

## Setup
```{r load-packages, message=FALSE, warning=FALSE}
# Load libraries
library(rprojroot)
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(AUCell)
library(msigdbr)
library(pheatmap)

# Define directories
root_dir <- find_root(has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "murine-cart-tumor")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

# Source custom theme
source(file.path(root_dir, "figures", "theme.R"))

# set random seed
set.seed(1234)
```

## Load Data
```{r load-data}
# Load Seurat object
dc_obj <- readRDS(file.path(results_dir, "cart_dc_reclustered.rds"))
```

# Gene set enrichment analysis

## AUCell scoring on MSigDB Hallmark Gene sets
```{r get-genesets, message=FALSE, warning=FALSE}
# msigdb hallmark
msigdb_hallmark <- msigdbr::msigdbr(species = "Mus musculus", category = "H") %>%
  dplyr::select(gs_name, gene_symbol) %>%
  dplyr::group_by(gs_name) %>%
  dplyr::summarise(genes = list(gene_symbol)) %>%
  deframe()
```

## Hallmark gene set activity by dc subcluster
```{r hallmark-activity, message=FALSE, warning=FALSE}
# AUCell on hallmark genesets
cells_rankings <- AUCell_buildRankings(GetAssayData(dc_obj, assay = "RNA", layer = "data"), nCores = 4, plotStats = TRUE)
hallmark_AUC <- AUCell_calcAUC(msigdb_hallmark, cells_rankings)

# add hallmark scores to seurat object
hallmark_scores_df <- as.data.frame(t(getAUC(hallmark_AUC)))
dc_obj <- AddMetaData(dc_obj, metadata = hallmark_scores_df)
```

# Subcluster vs pathway heatmap of AUCell scores
```{r subcluster-pathway-heatmap, fig.height=8, fig.width=16}
# z scores of AUCell scores across clusters per gene set
hallmark_scores_df$cluster = dc_obj$seurat_clusters

avg_hallmark_scores <- hallmark_scores_df %>%
  group_by(cluster) %>%
  summarise(across(starts_with("HALLMARK"), mean)) %>%
  column_to_rownames("cluster")

hallmark_z_scores <- scale(avg_hallmark_scores)
rownames(hallmark_z_scores) <- c("Cluster0", "Cluster1", "Cluster2", "Cluster3", "Cluster4", "Cluster5")

# Color scale
colors <- rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))
colors.use <- grDevices::colorRampPalette(colors = colors)(100)
breaks <- seq(-3, 3, length.out = 101)

# save heatmap as pdf
pdf(file = file.path(plot_dir, "reclustered_dc_subcluster_hallmark_auc_heatmap.pdf"), width = 16, height = 8)

hm <- pheatmap::pheatmap(mat = hallmark_z_scores,
                   color = colors.use,
                   border_color = "white",
                   breaks = breaks,
                   clustering_distance_rows = "correlation",
                  clustering_distance_cols = "correlation",
                  main = "Hallmark Pathway AUCell Activity across DC Subclusters")
print(hm)
dev.off()
```

## Session Info
```{r session-info}
sessionInfo()
```